INSERT INTO jogadores (nome, posicao, numero_camisa, time_id) VALUES
-- América-MG
('AméricaMG_GOL1', 'GOL', 1, (SELECT id FROM times WHERE nome='América-MG')),
('AméricaMG_GOL2', 'GOL', 12, (SELECT id FROM times WHERE nome='América-MG')),
('AméricaMG_ZAG1', 'ZAG', 3, (SELECT id FROM times WHERE nome='América-MG')),
('AméricaMG_ZAG2', 'ZAG', 4, (SELECT id FROM times WHERE nome='América-MG')),
('AméricaMG_LAT1', 'LAT', 2, (SELECT id FROM times WHERE nome='América-MG')),
('AméricaMG_LAT2', 'LAT', 6, (SELECT id FROM times WHERE nome='América-MG')),
('AméricaMG_MEI1', 'MEI', 5, (SELECT id FROM times WHERE nome='América-MG')),
('AméricaMG_MEI2', 'MEI', 8, (SELECT id FROM times WHERE nome='América-MG')),
('AméricaMG_MEI3', 'MEI', 10, (SELECT id FROM times WHERE nome='América-MG')),
('AméricaMG_ATA1', 'ATA', 7, (SELECT id FROM times WHERE nome='América-MG')),
('AméricaMG_ATA2', 'ATA', 9, (SELECT id FROM times WHERE nome='América-MG')),
('AméricaMG_ATA3', 'ATA', 11, (SELECT id FROM times WHERE nome='América-MG')),
('AméricaMG_RES1', 'MEI', 13, (SELECT id FROM times WHERE nome='América-MG')),
('AméricaMG_RES2', 'ZAG', 14, (SELECT id FROM times WHERE nome='América-MG')),
('AméricaMG_RES3', 'LAT', 15, (SELECT id FROM times WHERE nome='América-MG')),
('AméricaMG_RES4', 'MEI', 16, (SELECT id FROM times WHERE nome='América-MG')),
('AméricaMG_RES5', 'ATA', 17, (SELECT id FROM times WHERE nome='América-MG')),
('AméricaMG_RES6', 'GOL', 18, (SELECT id FROM times WHERE nome='América-MG')),
('AméricaMG_RES7', 'ZAG', 19, (SELECT id FROM times WHERE nome='América-MG')),
('AméricaMG_RES8', 'LAT', 20, (SELECT id FROM times WHERE nome='América-MG')),
('AméricaMG_RES9', 'MEI', 21, (SELECT id FROM times WHERE nome='América-MG')),
('AméricaMG_RES10', 'ATA', 22, (SELECT id FROM times WHERE nome='América-MG')),
('AméricaMG_RES11', 'ZAG', 23, (SELECT id FROM times WHERE nome='América-MG')),
('AméricaMG_RES12', 'LAT', 24, (SELECT id FROM times WHERE nome='América-MG')),
('AméricaMG_RES13', 'MEI', 25, (SELECT id FROM times WHERE nome='América-MG')),

