INSERT INTO times (nome, cidade) VALUES
('América-MG', 'Belo Horizonte'),
('Avaí', 'Florianópolis'),
('Botafogo-SP', 'Ribeirão Preto'),
('Brusque', 'Brusque'),
('Ceará', 'Fortaleza'),
('Chapecoense', 'Chapecó'),
('CRB', 'Maceió'),
('Goiás', 'Goiânia'),
('Guarani', 'Campinas'),
('Ituano', 'Itu'),
('Mirassol', 'Mirassol'),
('Novorizontino', 'Novo Horizonte'),
('Operário-PR', 'Ponta Grossa'),
('Ponte Preta', 'Campinas'),
('Santos', 'Santos'),
('Sport', 'Recife'),
('Vila Nova', 'Goiânia'),
('Amazonas', 'Manaus'),
('Paysandu', 'Belém'),
('Coritiba', 'Curitiba'),
('Londrina', 'Londrina');
